#!/bin/bash

get_keyboard_layout() {
    local layout
    layout=$(swaymsg -r -t get_inputs | jq -r '.[] | select(.type == "keyboard") | .xkb_active_layout_name' | head -n1)

    case "$layout" in
        "English (US)")
            echo "us"
            ;;
        "English (UK)")
            echo "gb"
            ;;
        *)
            echo "$layout"
            ;;
    esac
}

if [ "$1" = "cycle" ]
then
    # left click will cycle between these hard-coded layouts and refresh the waybar
    current=$(get_keyboard_layout)
    echo "cycled"

    if [ "$current" = "us" ]
    then
        swaymsg input type:keyboard xkb_layout gb
    else
        swaymsg input type:keyboard xkb_layout us
    fi

    pkill -RTMIN+14 waybar
else
    # If not cycling, just print the current layout
    layout=$(get_keyboard_layout)
    echo "$layout"
fi


