#!/bin/bash

mute=$(pactl get-sink-mute @DEFAULT_SINK@)

if [[ $mute == "Mute: no" ]]
then
    volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -n1)
    echo "${volume}"
else
    echo "MUTE"
fi

